e========================================
 "pxy" ./dev/config/environments/env_qa.sh
  ZAMA_GPXY_PHYS_HOSTS=("10.65.48.31" "10.65.48.32" "10.65.48.115")
  ZAMA_GPXY_VIRT_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_APXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_APXY_VIRT_HOSTS=("10.65.48.143" "10.65.48.148" "10.65.48.36")
  ZAMA_CPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_CPXY_VIRT_HOSTS=("10.65.48.150" "10.65.48.151" "10.65.48.40")
  ZAMA_FPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_FPXY_VIRT_HOSTS=("10.65.48.105" "10.65.48.146" "10.65.48.23")
  ZAMA_MPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_MPXY_VIRT_HOSTS=("10.65.48.154" "10.65.48.155" "10.65.48.42")
  ZAMA_EPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_EPXY_VIRT_HOSTS=("10.65.48.156" "10.65.48.157" "10.65.48.43")
  ZAMA_RPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_RPXY_VIRT_HOSTS=("10.65.48.152" "10.65.48.153" "10.65.48.41")
  ZAMA_YPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_YPXY_VIRT_HOSTS=("10.65.48.137" "10.65.48.145" "10.65.48.24")
  ZAMA_APIPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_APIPXY_VIRT_HOSTS=("10.65.48.158" "10.65.48.159" "10.65.48.44")
  ZAMA_TRACKER_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_MATCHER_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_ARTB_URI_HOSTNAME=${ZAMA_APXY_VIRT_HOSTS[0]}
  ZAMA_CRTB_URI_HOSTNAME=${ZAMA_CPXY_VIRT_HOSTS[0]}
  ZAMA_FRTB_URI_HOSTNAME=${ZAMA_FPXY_VIRT_HOSTS[0]}
  ZAMA_GRTB_URI_HOSTNAME=${ZAMA_GPXY_VIRT_HOSTS[0]}
  ZAMA_MRTB_URI_HOSTNAME=${ZAMA_GPXY_VIRT_HOSTS[0]}
  ZAMA_RRTB_URI_HOSTNAME=${ZAMA_GPXY_VIRT_HOSTS[0]}
  ZAMA_YRTB_URI_HOSTNAME=${ZAMA_YPXY_VIRT_HOSTS[0]}
  ZAMA_ERTB_URI_HOSTNAME=${ZAMA_EPXY_VIRT_HOSTS[0]}
  ZAMA_PRTB_URI_HOSTNAME=${ZAMA_PPXY_VIRT_HOSTS[0]}
# Description of ZAMA integration environment
#========================================

                 # 10.73.49.47     10.73.49.61
# ZAMA_GRTB_HOSTS=(rtbbid1us2-int1 rtbbid2us2-int1)
  ZAMA_GRTB_HOSTS=(10.73.49.47     10.73.49.61)
  ZAMA_GRTB_HOSTS_NUM=2
  ZAMA_GRTB_PORT=11100

                  # 10.73.49.49     10.73.49.59
# ZAMA_STCOL_HOSTS=(rtbmem1us2-int1 rtbmem2us2-int1)
  ZAMA_STCOL_HOSTS=(10.73.49.49     10.73.49.59)
  ZAMA_STCOL_PORT=11102
  ZAMA_STCOL_PERF_PORT=8802

  ZAMA_STCOL_POLL_PERIOD=1000

                         # 10.73.49.49
# ZAMA_STCOL_ACCESS_POINT="rtbmem1us2-int1"
  ZAMA_STCOL_ACCESS_POINT="10.73.49.49"
  ZAMA_STCOL_ACCESS_POINT_PORT=${ZAMA_STCOL_PORT}

# <<< ZAMA RTB DB configuration
                            #rtbmdb2us2-int1
  ZAMA_UMDB_NODES=(0000_0000@10.73.49.60)
  ZAMA_ASMDB_NODES=(${ZAMA_UMDB_NODES[@]})
  ZAMA_FCDB_NODES=(${ZAMA_UMDB_NODES[@]})

  ZAMA_RTBDB_GROUPS=(UMDB ASMDB FCDB)
  ZAMA_RTBDB_CONFIGS=(${ZAMA_RSVC_CFG} ${ZAMA_RSVC_CFG} ${ZAMA_RSVC_CFG})
  ZAMA_RTBDB_CREATE_CONFIG=1
# >>>

  ZAMA_GPXY_PHYS_HOSTS=("10.73.49.47" "10.73.49.61")
  ZAMA_GPXY_VIRT_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})

  ZAMA_APXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_APXY_VIRT_HOSTS=("__specify_appnexus_proxy_virt_IP_on_bidders__")

  ZAMA_CPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_CPXY_VIRT_HOSTS=("__specify_contextweb_proxy_virt_IP_on_bid01__" "__specify_contextweb_proxy_virt_IP_on_bid02__")

  ZAMA_FPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_FPXY_VIRT_HOSTS=("10.73.49.55" "10.73.49.64")

  ZAMA_RPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_RPXY_VIRT_HOSTS=("__specify_rubicon_proxy_virt_IP_on_bid01__" "__specify_rubicon_proxy_virt_IP_on_bid02__")

  ZAMA_YPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_YPXY_VIRT_HOSTS=("10.73.49.56" "10.73.49.65")

  ZAMA_TRACKER_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_TRACKER_VIRT_HOSTS=("10.73.49.45" "10.73.49.62")

  ZAMA_CLK_TRACKER_PHYS_HOSTS=(${ZAMA_TRACKER_PHYS_HOSTS[@]})
  ZAMA_CLK_TRACKER_VIRT_HOSTS=("__specify_clk_tracker_virt_IP_on_bid1__" "__specify_clk_tracker_virt_IP_on_bid2__")

  ZAMA_CNV_TRACKER_PHYS_HOSTS=(${ZAMA_TRACKER_PHYS_HOSTS[@]})
  ZAMA_CNV_TRACKER_VIRT_HOSTS=("__specify_cnv_tracker_virt_IP_on_bid1__" "__specify_cnv_tracker_virt_IP_on_bid2__")

  ZAMA_MATCHER_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_MATCHER_VIRT_HOSTS=("10.73.49.54" "10.73.49.63")

  ZAMA_ARTB_URI_HOSTNAME=${ZAMA_APXY_VIRT_HOSTS[0]}
  ZAMA_CRTB_URI_HOSTNAME=${ZAMA_CPXY_VIRT_HOSTS[0]}
  ZAMA_FRTB_URI_HOSTNAME=${ZAMA_FPXY_VIRT_HOSTS[0]}
  ZAMA_GRTB_URI_HOSTNAME=${ZAMA_GPXY_VIRT_HOSTS[0]}
  ZAMA_RRTB_URI_HOSTNAME=${ZAMA_GPXY_VIRT_HOSTS[0]}
  ZAMA_YRTB_URI_HOSTNAME=${ZAMA_YPXY_VIRT_HOSTS[0]}

  ZAMA_GTRK_URI_HOSTNAME="tracker1-int.bidder7.mookie1.com"

  ZAMA_CTRK_URI_HOSTNAME=${ZAMA_GTRK_URI_HOSTNAME}
  ZAMA_FTRK_URI_HOSTNAME=${ZAMA_GTRK_URI_HOSTNAME}
  ZAMA_RTRK_URI_HOSTNAME=${ZAMA_GTRK_URI_HOSTNAME}
  ZAMA_YTRK_URI_HOSTNAME=${ZAMA_GTRK_URI_HOSTNAME}

  ZAMA_CLTRK_URI_HOSTNAME="tracker2-int.bidder7.mookie1.com"
  ZAMA_CVTRK_URI_HOSTNAME="tracker3-int.bidder7.mookie1.com"

  ZAMA_MATCHER_URI_HOSTNAME="matcher1-int.bidder7.mookie1.com"

  ZAMA_AMTCH_URI_HOSTNAME="matcher-apx.bidder7.mookie1.com"
  ZAMA_CMTCH_URI_HOSTNAME="matcher-cwb.bidder7.mookie1.com"
  ZAMA_GMTCH_URI_HOSTNAME=${ZAMA_MATCHER_URI_HOSTNAME}
  ZAMA_RMTCH_URI_HOSTNAME="matcher-rbc.bidder7.mookie1.com"
  ZAMA_YMTCH_URI_HOSTNAME=${ZAMA_MATCHER_URI_HOSTNAME}

  ZWF_DEFAULT_PORT=11200

                 # rtbsloop1us2-int1
  ZWF_LGRDR_HOSTS=(10.73.49.50)
  ZWF_LGRDR_PORT=${ZWF_DEFAULT_PORT}

                 # rtbmem1us2-int1 rtbmem2us2-int1
  ZWF_SCFDR_HOSTS=(10.73.49.49     10.73.49.59)
  ZWF_SCFDR_PORT=${ZWF_DEFAULT_PORT}

  ZWF_FCFDR_HOSTS=${ZWF_LGRDR_HOSTS}
  ZWF_FCFDR_PORT=11202

  ZWF_BID_FILTERING_TYPE=""

  ZAMA_MATCHER_APPNEXUS_CM_URI="http://ib.adnxs.com/getuid?http://${ZAMA_AMTCH_URI_HOSTNAME}${ZAMA_MATCHER_APPNEXUS_ENTRY_URI_PATH}?adnxs_uid="

  ZAMA_COMMON_LOG_LEVEL=debug
  ZAMA_GRTB_PROXY_TIMEOUT=2000

  ZAMA_GRTB_STALE_SLEEP_PERIOD_SEC=60
  ZAMA_GRTB_MAX_STALE_BIDS=10

  ZAMA_GRTB_LOG_FLAGS="LOG_GEO LOG_EXCHANGE_INFO"

  ZAMA_PRIMARY_DB_HOST="10.65.47.214"
  ZAMA_PRIMARY_DB_SVCNAME="I1ZAP.DECIDEINTERACTIVE.COM"
  ZAMA_PRIMARY_DB_USER="ZAPSEC2"
  ZAMA_PRIMARY_DB_PSWD="ZAPSEC2"
