#========================================
# Description of ZAMA STG environment
#========================================

  ZAMA_GRTB_HOSTS=(esmbid1us2-dev1 esmbid2us2-dev1 esmbid3us2-dev1 esmbid4us2-dev1)
  ZAMA_GRTB_HOSTS_NUM=4
  ZAMA_GRTB_PORT=11100

  ZAMA_STCOL_HOSTS=(esmmem1us2-dev1 esmmem2us2-dev1)
  ZAMA_STCOL_PORT=11102
  ZAMA_STCOL_PERF_PORT=8802

  # 5 min
  ZAMA_STCOL_POLL_PERIOD=300000

  ZAMA_STCOL_ACCESS_POINT="esmmem1us2-dev1"
  ZAMA_STCOL_ACCESS_POINT_PORT=${ZAMA_STCOL_PORT}

# <<< ZAMA RTB DB configuration
                            #10.65.48.252                    10.65.48.252
  ZAMA_UMDB_NODES=(0000_0000@esmmdb1us2-dev1:6385   0001_0000@esmmdb2us2-dev1:6390)
  ZAMA_ASMDB_NODES=(${ZAMA_UMDB_NODES[@]})
  ZAMA_FCDB_NODES=(${ZAMA_UMDB_NODES[@]})

  ZAMA_RTBDB_GROUPS=(UMDB ASMDB FCDB)
  ZAMA_RTBDB_CONFIGS=(${ZAMA_RSVC_CFG} ${ZAMA_RSVC_CFG} ${ZAMA_RSVC_CFG})
  ZAMA_RTBDB_CREATE_CONFIG=1
# >>>

  ZAMA_GPXY_PHYS_HOSTS=("10.68.20.30" "10.68.20.40")
  ZAMA_GPXY_VIRT_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})

  ZAMA_APXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_APXY_VIRT_HOSTS=("10.68.20.37"  "10.68.20.47")

  ZAMA_CPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_CPXY_VIRT_HOSTS=("10.68.20.38" "10.68.20.48")

  ZAMA_EPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_EPXY_VIRT_HOSTS=("10.68.20.30"  "10.68.20.40")

  ZAMA_FPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_FPXY_VIRT_HOSTS=("10.68.20.33" "10.68.20.43")

  ZAMA_MPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_MPXY_VIRT_HOSTS=("__specify_admeld_proxy_virt_host-1__"  "__specify_admeld_proxy_virt_host-2__")

  ZAMA_YPXY_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_YPXY_VIRT_HOSTS=("10.68.20.46" "10.68.20.36")

  ZAMA_TRACKER_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_TRACKER_VIRT_HOSTS=("10.68.20.31" "10.68.20.41")

  ZAMA_CLK_TRACKER_PHYS_HOSTS=(${ZAMA_TRACKER_PHYS_HOSTS[@]})
  ZAMA_CLK_TRACKER_VIRT_HOSTS=("10.68.20.34" "10.68.20.44")

  ZAMA_CNV_TRACKER_PHYS_HOSTS=(${ZAMA_TRACKER_PHYS_HOSTS[@]})
  ZAMA_CNV_TRACKER_VIRT_HOSTS=("10.68.20.35" "10.68.20.45")

  ZAMA_MATCHER_PHYS_HOSTS=(${ZAMA_GPXY_PHYS_HOSTS[@]})
  ZAMA_MATCHER_VIRT_HOSTS=("10.68.20.32" "10.68.20.42")

  ZAMA_ARTB_URI_HOSTNAME=${ZAMA_APXY_VIRT_HOSTS[0]}
  ZAMA_CRTB_URI_HOSTNAME=${ZAMA_CPXY_VIRT_HOSTS[0]}
  ZAMA_ERTB_URI_HOSTNAME=${ZAMA_EPXY_VIRT_HOSTS[0]}
  ZAMA_FRTB_URI_HOSTNAME=${ZAMA_FPXY_VIRT_HOSTS[0]}
  ZAMA_GRTB_URI_HOSTNAME=${ZAMA_GPXY_VIRT_HOSTS[0]}
  ZAMA_MRTB_URI_HOSTNAME=${ZAMA_YPXY_VIRT_HOSTS[0]}
  ZAMA_YRTB_URI_HOSTNAME=${ZAMA_YPXY_VIRT_HOSTS[0]}

  ZAMA_GTRK_URI_HOSTNAME=${ZAMA_TRACKER_VIRT_HOSTS[0]}

  ZAMA_CTRK_URI_HOSTNAME=${ZAMA_GTRK_URI_HOSTNAME}
  ZAMA_ETRK_URI_HOSTNAME=${ZAMA_GTRK_URI_HOSTNAME}
  ZAMA_FTRK_URI_HOSTNAME=${ZAMA_GTRK_URI_HOSTNAME}
  ZAMA_RTRK_URI_HOSTNAME=${ZAMA_GTRK_URI_HOSTNAME}
  ZAMA_MTRK_URI_HOSTNAME=${ZAMA_GTRK_URI_HOSTNAME}
  ZAMA_YTRK_URI_HOSTNAME=${ZAMA_GTRK_URI_HOSTNAME}

  ZAMA_CLTRK_URI_HOSTNAME=${ZAMA_CLK_TRACKER_VIRT_HOSTS[0]}
  ZAMA_CVTRK_URI_HOSTNAME=${ZAMA_CNV_TRACKER_VIRT_HOSTS[0]}

  ZAMA_MATCHER_URI_HOSTNAME=${ZAMA_MATCHER_VIRT_HOSTS[0]}

  ZAMA_AMTCH_URI_HOSTNAME=${ZAMA_MATCHER_URI_HOSTNAME}
  ZAMA_CMTCH_URI_HOSTNAME=${ZAMA_MATCHER_URI_HOSTNAME}
  ZAMA_GMTCH_URI_HOSTNAME=${ZAMA_MATCHER_URI_HOSTNAME}
  ZAMA_YMTCH_URI_HOSTNAME=${ZAMA_MATCHER_URI_HOSTNAME}

  ZWF_DEFAULT_PORT=11200

                 # rtbsloop
  ZWF_LGRDR_HOSTS=(10.68.20.76)
  ZWF_LGRDR_PORT=${ZWF_DEFAULT_PORT}

                 # rtbmem rtbmem
  ZWF_SCFDR_HOSTS=(10.68.20.74 10.68.20.75)
  ZWF_SCFDR_PORT=${ZWF_DEFAULT_PORT}

  ZWF_FCFDR_HOSTS=${ZWF_LGRDR_HOSTS}
  ZWF_FCFDR_PORT=11202

  ZWF_BID_FILTERING_TYPE=""

  ZAMA_COMMON_LOG_LEVEL=trace
  ZAMA_GRTB_PROXY_TIMEOUT=2000

  ZAMA_GRTB_STALE_SLEEP_PERIOD_SEC=60
  ZAMA_GRTB_MAX_STALE_BIDS=5000

  ZAMA_GRTB_LOG_FLAGS="LOG_GEO LOG_EXCHANGE_INFO"